"""cascade delete for rating to movie relation

Revision ID: e6c63fd6af83
Revises: da12e2999e38
Create Date: 2026-01-01 02:20:59.781272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c63fd6af83'
down_revision: Union[str, Sequence[str], None] = 'da12e2999e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ratings_movie_id_fkey'), 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key(op.f('ratings_movie_id_fkey'), 'ratings', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
