from typing import Generic, Protocol, TypeVar

from ..model import Entity


TEntity = TypeVar("TEntity", bound=Entity)


class Repository(Protocol, Generic[TEntity]):
    def get(self, id: int) -> TEntity: ...
    def get_all(self) -> list[TEntity]: ...
    def insert(self, entity: TEntity) -> None: ...
    def delete(self, entity: TEntity) -> None: ...
    def delete_by_id(self, id: int) -> None: ...
    def count(self) -> int: ...

